import type { KindCategory } from './syntax-kinds'

// The complete controlled-English vocabulary: one entry per translated
// SyntaxKind, generated against TypeScript 5.9.3 and reviewed by hand.
// Every example is executable: vocabulary.test.ts parses exampleSource with
// the real engine and requires the render to equal exampleEnglish exactly,
// so this table can never drift from the implementation. Examples are
// complete tiny programs (rendered whole-file) so the expected text needs
// no executor cleverness and shows the construct in real context.

export interface VocabularyEntry {
  /** Canonical SyntaxKind name (never a deprecated alias). */
  syntaxKind: string
  /** The compiler-API node interface the entry describes. */
  nodeInterface: string
  category: KindCategory
  typescriptOnly: boolean
  /** The fixed head phrase — the one canonical English for the construct. */
  canonicalEnglish: string
  /** The full template with child slots, () alternatives and [] options. */
  englishTemplate: string
  /** Child slots in evaluation order. */
  children: string[]
  evaluationOrder: string
  /** File name the example parses as (default example.ts; JSX uses .tsx). */
  exampleFile?: string
  exampleSource: string
  exampleEnglish: string
  /** Which semantic level the wording needs. The engine is parser-only, so
   *  every entry is 'none' (Level 1) — kept per entry because the spec's
   *  table requires the field and a future Level-2 layer would set it. */
  semanticInfoRequired: 'none'
  notes?: string
}

export const VOCABULARY: readonly VocabularyEntry[] = [
  {
    syntaxKind: 'NumericLiteral',
    nodeInterface: 'ts.NumericLiteral',
    category: 'literal',
    typescriptOnly: false,
    canonicalEnglish: "number",
    englishTemplate: "number {raw source text}",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const timeout = 60_000;",
    exampleEnglish: "declare constant `timeout` and initialize it to number 60_000",
    semanticInfoRequired: 'none',
    notes: "Raw source text preserves numeric separators and radix.",
  },
  {
    syntaxKind: 'BigIntLiteral',
    nodeInterface: 'ts.BigIntLiteral',
    category: 'literal',
    typescriptOnly: false,
    canonicalEnglish: "bigint",
    englishTemplate: "bigint {text}",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const big = 42n;",
    exampleEnglish: "declare constant `big` and initialize it to bigint 42n",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'StringLiteral',
    nodeInterface: 'ts.StringLiteral',
    category: 'literal',
    typescriptOnly: false,
    canonicalEnglish: "string",
    englishTemplate: "string {JSON-quoted text}",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const greeting = \"hi\";",
    exampleEnglish: "declare constant `greeting` and initialize it to string \"hi\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'RegularExpressionLiteral',
    nodeInterface: 'ts.RegularExpressionLiteral',
    category: 'literal',
    typescriptOnly: false,
    canonicalEnglish: "regular expression",
    englishTemplate: "regular expression {raw literal}",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const pattern = /ab+c/gi;",
    exampleEnglish: "declare constant `pattern` and initialize it to regular expression /ab+c/gi",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'NoSubstitutionTemplateLiteral',
    nodeInterface: 'ts.NoSubstitutionTemplateLiteral',
    category: 'literal',
    typescriptOnly: false,
    canonicalEnglish: "template string",
    englishTemplate: "template string {JSON-quoted text}",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const plain = `plain`;",
    exampleEnglish: "declare constant `plain` and initialize it to template string \"plain\"",
    semanticInfoRequired: 'none',
    notes: "Distinct wording from string so backtick and quote literals never read the same.",
  },
  {
    syntaxKind: 'Identifier',
    nodeInterface: 'ts.Identifier',
    category: 'name',
    typescriptOnly: false,
    canonicalEnglish: "backticked name",
    englishTemplate: "`{text}`",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "order;",
    exampleEnglish: "`order`",
    semanticInfoRequired: 'none',
    notes: "Names remain names: no prose is invented around an identifier.",
  },
  {
    syntaxKind: 'PrivateIdentifier',
    nodeInterface: 'ts.PrivateIdentifier',
    category: 'name',
    typescriptOnly: false,
    canonicalEnglish: "backticked name",
    englishTemplate: "`#{text}`",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "class Vault { #secret = 1; }",
    exampleEnglish: "declare class `Vault`\nmembers:\n    field `#secret` and initialize it to number 1",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TrueKeyword',
    nodeInterface: 'ts.TrueLiteral',
    category: 'keyword',
    typescriptOnly: false,
    canonicalEnglish: "true",
    englishTemplate: "true",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const flag = true;",
    exampleEnglish: "declare constant `flag` and initialize it to true",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'FalseKeyword',
    nodeInterface: 'ts.FalseLiteral',
    category: 'keyword',
    typescriptOnly: false,
    canonicalEnglish: "false",
    englishTemplate: "false",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const flag = false;",
    exampleEnglish: "declare constant `flag` and initialize it to false",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'NullKeyword',
    nodeInterface: 'ts.NullLiteral',
    category: 'keyword',
    typescriptOnly: false,
    canonicalEnglish: "null",
    englishTemplate: "null",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const empty = null;",
    exampleEnglish: "declare constant `empty` and initialize it to null",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ThisKeyword',
    nodeInterface: 'ts.ThisExpression',
    category: 'keyword',
    typescriptOnly: false,
    canonicalEnglish: "`this`",
    englishTemplate: "`this`",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "function self() { return this; }",
    exampleEnglish: "declare function `self`\nwith no parameters\nbody:\n    return `this`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'SuperKeyword',
    nodeInterface: 'ts.SuperExpression',
    category: 'keyword',
    typescriptOnly: false,
    canonicalEnglish: "`super`",
    englishTemplate: "`super`",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "class Child extends Base { constructor() { super(); } }",
    exampleEnglish: "declare class `Child`\nextending `Base`\nmembers:\n    constructor\n    with no parameters\n    body:\n        call `super` with no arguments",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ImportKeyword',
    nodeInterface: 'ts.ImportExpression',
    category: 'keyword',
    typescriptOnly: false,
    canonicalEnglish: "`import`",
    englishTemplate: "`import`",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const mod = await import(\"./m\");",
    exampleEnglish: "declare constant `mod`\nand initialize it to:\n    await:\n        call `import`\n        with argument string \"./m\"",
    semanticInfoRequired: 'none',
    notes: "A dynamic import is a call whose callee is `import`.",
  },
  {
    syntaxKind: 'QualifiedName',
    nodeInterface: 'ts.QualifiedName',
    category: 'name',
    typescriptOnly: false,
    canonicalEnglish: "dotted name",
    englishTemplate: "`{left}.{right}`",
    children: ["left","right"],
    evaluationOrder: "left, then right",
    exampleSource: "let wait: ns.Duration;",
    exampleEnglish: "declare variable `wait` with type `ns.Duration`",
    semanticInfoRequired: 'none',
    notes: "A dotted entity name renders as one backticked path.",
  },
  {
    syntaxKind: 'AnyKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "any",
    englishTemplate: "any",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let loose: any;",
    exampleEnglish: "declare variable `loose` with type any",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'UnknownKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "unknown",
    englishTemplate: "unknown",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let mystery: unknown;",
    exampleEnglish: "declare variable `mystery` with type unknown",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'NeverKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "never",
    englishTemplate: "never",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let impossible: never;",
    exampleEnglish: "declare variable `impossible` with type never",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'VoidKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'keyword',
    typescriptOnly: false,
    canonicalEnglish: "void",
    englishTemplate: "void",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "function log(): void {}",
    exampleEnglish: "declare function `log`\nwith no parameters\nreturn type:\n    void\nbody:\n    no statements",
    semanticInfoRequired: 'none',
    notes: "The void *type*; the void operator is VoidExpression.",
  },
  {
    syntaxKind: 'UndefinedKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "undefined",
    englishTemplate: "undefined",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let missing: undefined;",
    exampleEnglish: "declare variable `missing` with type undefined",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'StringKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "string",
    englishTemplate: "string",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let name: string;",
    exampleEnglish: "declare variable `name` with type string",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'NumberKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "number",
    englishTemplate: "number",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let count: number;",
    exampleEnglish: "declare variable `count` with type number",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'BooleanKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "boolean",
    englishTemplate: "boolean",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let ready: boolean;",
    exampleEnglish: "declare variable `ready` with type boolean",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'BigIntKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "bigint",
    englishTemplate: "bigint",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let big: bigint;",
    exampleEnglish: "declare variable `big` with type bigint",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'SymbolKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "symbol",
    englishTemplate: "symbol",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let token: symbol;",
    exampleEnglish: "declare variable `token` with type symbol",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ObjectKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "object",
    englishTemplate: "object",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "let box: object;",
    exampleEnglish: "declare variable `box` with type object",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'IntrinsicKeyword',
    nodeInterface: 'ts.KeywordTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "intrinsic",
    englishTemplate: "intrinsic",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "type Upper = intrinsic;",
    exampleEnglish: "declare type alias `Upper` as intrinsic",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'PropertyAccessExpression',
    nodeInterface: 'ts.PropertyAccessExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "property … of …",
    englishTemplate: "(property | optional property) `{name}` of {expression}",
    children: ["name","expression"],
    evaluationOrder: "object expression evaluates first; the name is static",
    exampleSource: "user.email;",
    exampleEnglish: "property `email` of `user`",
    semanticInfoRequired: 'none',
    notes: "`?.` reads \"optional property\" so foo.bar and foo?.bar never match.",
  },
  {
    syntaxKind: 'ElementAccessExpression',
    nodeInterface: 'ts.ElementAccessExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "element … of …",
    englishTemplate: "(element | optional element) {argumentExpression} of {expression}",
    children: ["argumentExpression","expression"],
    evaluationOrder: "object expression, then index expression",
    exampleSource: "items[0];",
    exampleEnglish: "element number 0 of `items`",
    semanticInfoRequired: 'none',
    notes: "Distinct from property access so foo.bar and foo[\"bar\"] never read the same.",
  },
  {
    syntaxKind: 'CallExpression',
    nodeInterface: 'ts.CallExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "call",
    englishTemplate: "(call | optionally call) {expression} [with type argument(s) …] (with no arguments | with argument … | with arguments: …)",
    children: ["expression (callee)","typeArguments","arguments"],
    evaluationOrder: "callee, then arguments left to right",
    exampleSource: "processPayment(order);",
    exampleEnglish: "call `processPayment`\nwith argument `order`",
    semanticInfoRequired: 'none',
    notes: "Any call with arguments is a block; nested calls stay visibly nested.",
  },
  {
    syntaxKind: 'NewExpression',
    nodeInterface: 'ts.NewExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "construct a new",
    englishTemplate: "construct a new {expression} [with type argument(s) …] [with no arguments | with argument … | with arguments: …]",
    children: ["expression (constructor)","typeArguments","arguments"],
    evaluationOrder: "constructor expression, then arguments left to right",
    exampleSource: "const failure = new Error(\"boom\");",
    exampleEnglish: "declare constant `failure`\nand initialize it to:\n    construct a new `Error`\n    with argument string \"boom\"",
    semanticInfoRequired: 'none',
    notes: "`new Foo` (no argument list) carries no argument segment, distinct from `new Foo()`.",
  },
  {
    syntaxKind: 'BinaryExpression',
    nodeInterface: 'ts.BinaryExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "operator phrase between operands",
    englishTemplate: "{left} {operator phrase} {right} — assignments read \"assign {left} the value {right}\"",
    children: ["left","operatorToken","right"],
    evaluationOrder: "left, then right (assignment targets are named first)",
    exampleSource: "const total = price * quantity;",
    exampleEnglish: "declare constant `total` and initialize it to `price` multiplied by `quantity`",
    semanticInfoRequired: 'none',
    notes: "Every operator has exactly one phrase (see BINARY_OPERATOR_PHRASES / COMPOUND_ASSIGNMENT_PHRASES); nested binary operands are explicitly grouped.",
  },
  {
    syntaxKind: 'PrefixUnaryExpression',
    nodeInterface: 'ts.PrefixUnaryExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "not / negative / positive / bitwise-NOT / increment / decrement",
    englishTemplate: "{operator phrase} {operand}",
    children: ["operand"],
    evaluationOrder: "operand only",
    exampleSource: "const negated = -count;",
    exampleEnglish: "declare constant `negated` and initialize it to negative `count`",
    semanticInfoRequired: 'none',
    notes: "++x/--x read \"increment/decrement … and yield the new value\".",
  },
  {
    syntaxKind: 'PostfixUnaryExpression',
    nodeInterface: 'ts.PostfixUnaryExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "increment / decrement … and yield the previous value",
    englishTemplate: "increment|decrement {operand} and yield the previous value",
    children: ["operand"],
    evaluationOrder: "operand only",
    exampleSource: "count++;",
    exampleEnglish: "increment `count` and yield the previous value",
    semanticInfoRequired: 'none',
    notes: "The yielded-value wording is what separates x++ from ++x.",
  },
  {
    syntaxKind: 'ParenthesizedExpression',
    nodeInterface: 'ts.ParenthesizedExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "explicit grouping",
    englishTemplate: "({expression}) inline, or \"group of:\" as a block",
    children: ["expression"],
    evaluationOrder: "inner expression only",
    exampleSource: "const total = (base + tax) * 2;",
    exampleEnglish: "declare constant `total` and initialize it to (`base` plus `tax`) multiplied by number 2",
    semanticInfoRequired: 'none',
    notes: "Grouping is preserved so (a + b) * c and a + b * c can never read the same.",
  },
  {
    syntaxKind: 'ConditionalExpression',
    nodeInterface: 'ts.ConditionalExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "if … then yield … otherwise yield …",
    englishTemplate: "if {condition} then yield {whenTrue} otherwise yield {whenFalse}",
    children: ["condition","whenTrue","whenFalse"],
    evaluationOrder: "condition, then exactly one branch at runtime",
    exampleSource: "const label = isActive ? \"on\" : \"off\";",
    exampleEnglish: "declare constant `label`\nand initialize it to:\n    if `isActive` is truthy then yield string \"on\" otherwise yield string \"off\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'AwaitExpression',
    nodeInterface: 'ts.AwaitExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "await",
    englishTemplate: "await {expression}",
    children: ["expression"],
    evaluationOrder: "operand evaluates, then the result is awaited",
    exampleSource: "const user = await findUser();",
    exampleEnglish: "declare constant `user`\nand initialize it to:\n    await:\n        call `findUser` with no arguments",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'YieldExpression',
    nodeInterface: 'ts.YieldExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "yield / yield each value of",
    englishTemplate: "yield [{expression}] | yield each value of {expression}",
    children: ["expression"],
    evaluationOrder: "operand evaluates, then the generator suspends",
    exampleSource: "function* count() { yield 1; }",
    exampleEnglish: "declare generator function `count`\nwith no parameters\nbody:\n    yield number 1",
    semanticInfoRequired: 'none',
    notes: "`yield*` reads \"yield each value of\", distinct from plain yield.",
  },
  {
    syntaxKind: 'TypeOfExpression',
    nodeInterface: 'ts.TypeOfExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "the type name of",
    englishTemplate: "the type name of {expression}",
    children: ["expression"],
    evaluationOrder: "operand only",
    exampleSource: "const kind = typeof value;",
    exampleEnglish: "declare constant `kind` and initialize it to the type name of `value`",
    semanticInfoRequired: 'none',
    notes: "Runtime typeof; the type-position typeof is TypeQuery.",
  },
  {
    syntaxKind: 'VoidExpression',
    nodeInterface: 'ts.VoidExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "evaluate … and yield undefined",
    englishTemplate: "evaluate {expression} and yield undefined",
    children: ["expression"],
    evaluationOrder: "operand only",
    exampleSource: "void promise;",
    exampleEnglish: "evaluate `promise` and yield undefined",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'DeleteExpression',
    nodeInterface: 'ts.DeleteExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "delete",
    englishTemplate: "delete {expression}",
    children: ["expression"],
    evaluationOrder: "operand only",
    exampleSource: "delete cache.entry;",
    exampleEnglish: "delete property `entry` of `cache`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'SpreadElement',
    nodeInterface: 'ts.SpreadElement',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "spread of",
    englishTemplate: "spread of {expression}",
    children: ["expression"],
    evaluationOrder: "operand only",
    exampleSource: "const all = [...head, tail];",
    exampleEnglish: "declare constant `all`\nand initialize it to:\n    an array literal of:\n        spread of `head`\n        `tail`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TemplateExpression',
    nodeInterface: 'ts.TemplateExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "template string joining",
    englishTemplate: "template string joining: text …, value of …, …",
    children: ["head","templateSpans"],
    evaluationOrder: "chunks in source order",
    exampleSource: "const message = `Hello ${name}!`;",
    exampleEnglish: "declare constant `message`\nand initialize it to:\n    template string joining:\n        text \"Hello \"\n        value of `name`\n        text \"!\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TaggedTemplateExpression',
    nodeInterface: 'ts.TaggedTemplateExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "call tag … with template …",
    englishTemplate: "call tag {tag} with template {template}",
    children: ["tag","template"],
    evaluationOrder: "tag, then the template parts",
    exampleSource: "const query = sql`SELECT 1`;",
    exampleEnglish: "declare constant `query`\nand initialize it to:\n    call tag `sql` using template string \"SELECT 1\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ObjectLiteralExpression',
    nodeInterface: 'ts.ObjectLiteralExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "an object literal with",
    englishTemplate: "an empty object literal | an object literal with: {properties}",
    children: ["properties"],
    evaluationOrder: "properties in source order",
    exampleSource: "const point = { x: 1, y };",
    exampleEnglish: "declare constant `point`\nand initialize it to:\n    an object literal with:\n        property `x` set to number 1\n        shorthand property `y`",
    semanticInfoRequired: 'none',
    notes: "Shorthand `{ y }` reads \"shorthand property\", distinct from `{ y: y }`.",
  },
  {
    syntaxKind: 'ArrayLiteralExpression',
    nodeInterface: 'ts.ArrayLiteralExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "an array literal of",
    englishTemplate: "an empty array literal | an array literal of: {elements}",
    children: ["elements"],
    evaluationOrder: "elements in source order",
    exampleSource: "const list = [1, 2, 3];",
    exampleEnglish: "declare constant `list` and initialize it to an array literal of number 1, number 2 and number 3",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'OmittedExpression',
    nodeInterface: 'ts.OmittedExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "a hole",
    englishTemplate: "a hole",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const sparse = [1, , 3];",
    exampleEnglish: "declare constant `sparse` and initialize it to an array literal of number 1, a hole and number 3",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ArrowFunction',
    nodeInterface: 'ts.ArrowFunction',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "arrow function",
    englishTemplate: "arrow function / {parameters} / (returning {expression} | body: {statements})",
    children: ["typeParameters","parameters","type","body"],
    evaluationOrder: "parameters bind when called; the body runs per call",
    exampleSource: "const ids = items.map(item => item.id);",
    exampleEnglish: "declare constant `ids`\nand initialize it to:\n    call property `map` of `items`\n    with argument:\n        arrow function\n        parameter `item`\n        returning property `id` of `item`",
    semanticInfoRequired: 'none',
    notes: "A concise body reads \"returning\"; a block body reads \"body:\" — the two source forms stay distinct.",
  },
  {
    syntaxKind: 'FunctionExpression',
    nodeInterface: 'ts.FunctionExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "function expression",
    englishTemplate: "[asynchronous] [generator] function expression [`{name}`] / {parameters} / body: {statements}",
    children: ["name","typeParameters","parameters","type","body"],
    evaluationOrder: "parameters bind when called; the body runs per call",
    exampleSource: "const run = function runner() { return 1; };",
    exampleEnglish: "declare constant `run`\nand initialize it to:\n    function expression `runner`\n    with no parameters\n    body:\n        return number 1",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ClassExpression',
    nodeInterface: 'ts.ClassExpression',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "class expression",
    englishTemplate: "class expression [`{name}`] / … class body …",
    children: ["name","typeParameters","heritageClauses","members"],
    evaluationOrder: "heritage evaluates first, then members in source order",
    exampleSource: "const Base = class Named {};",
    exampleEnglish: "declare constant `Base`\nand initialize it to:\n    class expression `Named`\n    with no members",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'AsExpression',
    nodeInterface: 'ts.AsExpression',
    category: 'expression',
    typescriptOnly: true,
    canonicalEnglish: "treated as type",
    englishTemplate: "{expression} treated as type {type}",
    children: ["expression","type"],
    evaluationOrder: "expression only; the assertion is compile-time",
    exampleSource: "const id = value as string;",
    exampleEnglish: "declare constant `id` and initialize it to `value` treated as type string",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'SatisfiesExpression',
    nodeInterface: 'ts.SatisfiesExpression',
    category: 'expression',
    typescriptOnly: true,
    canonicalEnglish: "checked to satisfy type",
    englishTemplate: "{expression} checked to satisfy type {type}",
    children: ["expression","type"],
    evaluationOrder: "expression only; the check is compile-time",
    exampleSource: "const config = { port: 1 } satisfies Config;",
    exampleEnglish: "declare constant `config`\nand initialize it to:\n    an object literal with:\n        property `port` set to number 1\n    checked to satisfy type `Config`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'NonNullExpression',
    nodeInterface: 'ts.NonNullExpression',
    category: 'expression',
    typescriptOnly: true,
    canonicalEnglish: "asserted non-null",
    englishTemplate: "{expression} asserted non-null",
    children: ["expression"],
    evaluationOrder: "expression only; the assertion is compile-time",
    exampleSource: "const name = account!.name;",
    exampleEnglish: "declare constant `name` and initialize it to property `name` of `account` asserted non-null",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TypeAssertionExpression',
    nodeInterface: 'ts.TypeAssertion',
    category: 'expression',
    typescriptOnly: true,
    canonicalEnglish: "cast to type … the value …",
    englishTemplate: "cast to type {type} the value {expression}",
    children: ["type","expression"],
    evaluationOrder: "expression only; the assertion is compile-time",
    exampleSource: "const port = <number>raw;",
    exampleEnglish: "declare constant `port` and initialize it to cast to type number the value `raw`",
    semanticInfoRequired: 'none',
    notes: "Angle-bracket assertions keep their own wording, distinct from `as`.",
  },
  {
    syntaxKind: 'ExpressionWithTypeArguments',
    nodeInterface: 'ts.ExpressionWithTypeArguments',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "with type argument(s)",
    englishTemplate: "{expression} with type argument(s) {typeArguments}",
    children: ["expression","typeArguments"],
    evaluationOrder: "expression only",
    exampleSource: "class List extends Collection<string> {}",
    exampleEnglish: "declare class `List`\nextending `Collection` with type argument string\nwith no members",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'MetaProperty',
    nodeInterface: 'ts.MetaProperty',
    category: 'expression',
    typescriptOnly: false,
    canonicalEnglish: "meta-property name",
    englishTemplate: "`new.target` | `import.meta`",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "const here = import.meta;",
    exampleEnglish: "declare constant `here` and initialize it to `import.meta`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ObjectBindingPattern',
    nodeInterface: 'ts.ObjectBindingPattern',
    category: 'binding',
    typescriptOnly: false,
    canonicalEnglish: "an object pattern binding",
    englishTemplate: "an object pattern binding: bind property …[ to …][ with default …] / bind the remaining properties to …",
    children: ["elements"],
    evaluationOrder: "properties read left to right",
    exampleSource: "const { name, age: years } = user;",
    exampleEnglish: "declare constant:\n    an object pattern binding:\n        bind property `name`\n        bind property `age` to `years`\nand initialize it to `user`",
    semanticInfoRequired: 'none',
    notes: "Shorthand `{ name }` has no \"to\" clause; `{ age: years }` binds property `age` to `years`.",
  },
  {
    syntaxKind: 'ArrayBindingPattern',
    nodeInterface: 'ts.ArrayBindingPattern',
    category: 'binding',
    typescriptOnly: false,
    canonicalEnglish: "an array pattern binding",
    englishTemplate: "an array pattern binding: bind element {i} to … / skip element {i} / bind the remaining elements to …",
    children: ["elements"],
    evaluationOrder: "elements read left to right by position",
    exampleSource: "const [first, , ...rest] = items;",
    exampleEnglish: "declare constant:\n    an array pattern binding:\n        bind element 0 to `first`\n        skip element 1\n        bind the remaining elements to `rest`\nand initialize it to `items`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'VariableStatement',
    nodeInterface: 'ts.VariableStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "declare …",
    englishTemplate: "declare (constant | variable | function-scoped variable | disposable constant | asynchronously disposable constant) …; several declarators wrap in \"in one declaration statement:\"",
    children: ["declarationList"],
    evaluationOrder: "declarators left to right",
    exampleSource: "let count = 0, step = 1;",
    exampleEnglish: "in one declaration statement:\n    declare variable `count` and initialize it to number 0\n    declare variable `step` and initialize it to number 1",
    semanticInfoRequired: 'none',
    notes: "The multi-declarator wrapper keeps `let a, b` distinct from two statements.",
  },
  {
    syntaxKind: 'Parameter',
    nodeInterface: 'ts.ParameterDeclaration',
    category: 'declaration',
    typescriptOnly: false,
    canonicalEnglish: "parameter",
    englishTemplate: "[modifier words] (parameter | optional parameter | rest parameter) {name} [with type {type}] [with default {initializer}]",
    children: ["modifiers","name","type","initializer"],
    evaluationOrder: "defaults evaluate at call time, left to right",
    exampleSource: "function greet(name: string) {}",
    exampleEnglish: "declare function `greet`\nparameters:\n    parameter `name` with type string\nbody:\n    no statements",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'Decorator',
    nodeInterface: 'ts.Decorator',
    category: 'declaration',
    typescriptOnly: false,
    canonicalEnglish: "decorator",
    englishTemplate: "decorated with: decorator {expression}",
    children: ["expression"],
    evaluationOrder: "decorator expressions evaluate before the decorated declaration is finalized",
    exampleSource: "@sealed class Config {}",
    exampleEnglish: "decorated with:\n    decorator `sealed`\ndeclare class `Config`\nwith no members",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'FunctionDeclaration',
    nodeInterface: 'ts.FunctionDeclaration',
    category: 'declaration',
    typescriptOnly: false,
    canonicalEnglish: "declare function",
    englishTemplate: "declare [modifier words] [generator] function `{name}` / [with type parameters:] / (parameters: | with no parameters) / [return type:] / (body: | with no body)",
    children: ["modifiers","name","typeParameters","parameters","type","body"],
    evaluationOrder: "parameters bind when called; the body runs per call",
    exampleSource: "async function getUser(id: string): Promise<User> {\n  return repository.find(id);\n}",
    exampleEnglish: "declare asynchronous function `getUser`\nparameters:\n    parameter `id` with type string\nreturn type:\n    type `Promise` with type argument `User`\nbody:\n    return:\n        call property `find` of `repository`\n        with argument `id`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ClassDeclaration',
    nodeInterface: 'ts.ClassDeclaration',
    category: 'declaration',
    typescriptOnly: false,
    canonicalEnglish: "declare class",
    englishTemplate: "declare [modifier words] class [`{name}`] / [decorated with:] / [extending …] / [implementing:] / (members: | with no members)",
    children: ["decorators","modifiers","name","typeParameters","heritageClauses","members"],
    evaluationOrder: "heritage evaluates first, then member initializers in source order",
    exampleSource: "export class User extends Base implements Named {}",
    exampleEnglish: "declare exported class `User`\nextending `Base`\nimplementing:\n    `Named`\nwith no members",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'PropertyDeclaration',
    nodeInterface: 'ts.PropertyDeclaration',
    category: 'class-member',
    typescriptOnly: false,
    canonicalEnglish: "field",
    englishTemplate: "[modifier words] (field | optional field) {name} [asserted as definitely assigned] [with type {type}] [and initialize it to {initializer}]",
    children: ["decorators","modifiers","name","type","initializer"],
    evaluationOrder: "initializers run per construction, in member order",
    exampleSource: "class User { readonly name = \"anon\"; }",
    exampleEnglish: "declare class `User`\nmembers:\n    readonly field `name` and initialize it to string \"anon\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'MethodDeclaration',
    nodeInterface: 'ts.MethodDeclaration',
    category: 'class-member',
    typescriptOnly: false,
    canonicalEnglish: "method",
    englishTemplate: "[modifier words] [generator] (method | optional method) {name} / … signature and body …",
    children: ["decorators","modifiers","name","typeParameters","parameters","type","body"],
    evaluationOrder: "parameters bind when called; the body runs per call",
    exampleSource: "class Repo { find(id: string) { return id; } }",
    exampleEnglish: "declare class `Repo`\nmembers:\n    method `find`\n    parameters:\n        parameter `id` with type string\n    body:\n        return `id`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'Constructor',
    nodeInterface: 'ts.ConstructorDeclaration',
    category: 'class-member',
    typescriptOnly: false,
    canonicalEnglish: "constructor",
    englishTemplate: "constructor / (parameters: | with no parameters) / (body: | with no body)",
    children: ["parameters","body"],
    evaluationOrder: "runs once per construction",
    exampleSource: "class User { constructor(name: string) {} }",
    exampleEnglish: "declare class `User`\nmembers:\n    constructor\n    parameters:\n        parameter `name` with type string\n    body:\n        no statements",
    semanticInfoRequired: 'none',
    notes: "Parameter-property modifiers (private name: …) render as modifier words on the parameter.",
  },
  {
    syntaxKind: 'GetAccessor',
    nodeInterface: 'ts.GetAccessorDeclaration',
    category: 'class-member',
    typescriptOnly: false,
    canonicalEnglish: "getter",
    englishTemplate: "[modifier words] getter {name} / [return type:] / (body: | with no body)",
    children: ["modifiers","name","type","body"],
    evaluationOrder: "runs on property read",
    exampleSource: "class User { get name() { return \"anon\"; } }",
    exampleEnglish: "declare class `User`\nmembers:\n    getter `name`\n    body:\n        return string \"anon\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'SetAccessor',
    nodeInterface: 'ts.SetAccessorDeclaration',
    category: 'class-member',
    typescriptOnly: false,
    canonicalEnglish: "setter",
    englishTemplate: "[modifier words] setter {name} / parameters: / (body: | with no body)",
    children: ["modifiers","name","parameters","body"],
    evaluationOrder: "runs on property write",
    exampleSource: "class User { set name(value: string) {} }",
    exampleEnglish: "declare class `User`\nmembers:\n    setter `name`\n    parameters:\n        parameter `value` with type string\n    body:\n        no statements",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ClassStaticBlockDeclaration',
    nodeInterface: 'ts.ClassStaticBlockDeclaration',
    category: 'class-member',
    typescriptOnly: false,
    canonicalEnglish: "static initialization block",
    englishTemplate: "static initialization block / body: {statements}",
    children: ["body"],
    evaluationOrder: "runs once when the class is evaluated",
    exampleSource: "class Config { static { setup(); } }",
    exampleEnglish: "declare class `Config`\nmembers:\n    static initialization block\n    body:\n        call `setup` with no arguments",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'SemicolonClassElement',
    nodeInterface: 'ts.SemicolonClassElement',
    category: 'class-member',
    typescriptOnly: false,
    canonicalEnglish: "an empty class member",
    englishTemplate: "an empty class member",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "class Empty { ; }",
    exampleEnglish: "declare class `Empty`\nmembers:\n    an empty class member",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'InterfaceDeclaration',
    nodeInterface: 'ts.InterfaceDeclaration',
    category: 'declaration',
    typescriptOnly: true,
    canonicalEnglish: "declare interface",
    englishTemplate: "declare [modifier words] interface `{name}` / [with type parameters:] / [extending:] / (members: | with no members)",
    children: ["modifiers","name","typeParameters","heritageClauses","members"],
    evaluationOrder: "declaration only; nothing evaluates",
    exampleSource: "interface User extends Named { age: number; }",
    exampleEnglish: "declare interface `User`\nextending:\n    `Named`\nmembers:\n    property `age` with type number",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'PropertySignature',
    nodeInterface: 'ts.PropertySignature',
    category: 'class-member',
    typescriptOnly: true,
    canonicalEnglish: "property (member)",
    englishTemplate: "[readonly] (property | optional property) {name} [with type {type}]",
    children: ["modifiers","name","type"],
    evaluationOrder: "declaration only",
    exampleSource: "interface User { name: string; }",
    exampleEnglish: "declare interface `User`\nmembers:\n    property `name` with type string",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'MethodSignature',
    nodeInterface: 'ts.MethodSignature',
    category: 'class-member',
    typescriptOnly: true,
    canonicalEnglish: "method (member)",
    englishTemplate: "(method | optional method) {name} / … signature …",
    children: ["name","typeParameters","parameters","type"],
    evaluationOrder: "declaration only",
    exampleSource: "interface Repo { find(id: string): void; }",
    exampleEnglish: "declare interface `Repo`\nmembers:\n    method `find`\n    parameters:\n        parameter `id` with type string\n    return type:\n        void",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'CallSignature',
    nodeInterface: 'ts.CallSignatureDeclaration',
    category: 'class-member',
    typescriptOnly: true,
    canonicalEnglish: "call signature",
    englishTemplate: "call signature / … signature …",
    children: ["typeParameters","parameters","type"],
    evaluationOrder: "declaration only",
    exampleSource: "interface Callable { (input: string): void; }",
    exampleEnglish: "declare interface `Callable`\nmembers:\n    call signature\n    parameters:\n        parameter `input` with type string\n    return type:\n        void",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ConstructSignature',
    nodeInterface: 'ts.ConstructSignatureDeclaration',
    category: 'class-member',
    typescriptOnly: true,
    canonicalEnglish: "construct signature",
    englishTemplate: "construct signature / … signature …",
    children: ["typeParameters","parameters","type"],
    evaluationOrder: "declaration only",
    exampleSource: "interface Factory { new (input: string): Widget; }",
    exampleEnglish: "declare interface `Factory`\nmembers:\n    construct signature\n    parameters:\n        parameter `input` with type string\n    return type:\n        `Widget`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'IndexSignature',
    nodeInterface: 'ts.IndexSignatureDeclaration',
    category: 'class-member',
    typescriptOnly: true,
    canonicalEnglish: "index signature",
    englishTemplate: "[modifier words] index signature key {name} of key type {keyType} with value type {type}",
    children: ["modifiers","parameter","type"],
    evaluationOrder: "declaration only",
    exampleSource: "interface Bag { [key: string]: number; }",
    exampleEnglish: "declare interface `Bag`\nmembers:\n    index signature key `key` of key type string with value type number",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TypeAliasDeclaration',
    nodeInterface: 'ts.TypeAliasDeclaration',
    category: 'declaration',
    typescriptOnly: true,
    canonicalEnglish: "declare type alias",
    englishTemplate: "declare [modifier words] type alias `{name}` [with type parameters:] as {type}",
    children: ["modifiers","name","typeParameters","type"],
    evaluationOrder: "declaration only",
    exampleSource: "type Result<T> = T | Error;",
    exampleEnglish: "declare type alias `Result`\nwith type parameters:\n    type parameter `T`\nas union type of `T` and `Error`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'EnumDeclaration',
    nodeInterface: 'ts.EnumDeclaration',
    category: 'declaration',
    typescriptOnly: true,
    canonicalEnglish: "declare enum",
    englishTemplate: "declare [modifier words] enum `{name}` / (members: | with no members) — member `{name}` [with value {initializer}]",
    children: ["modifiers","name","members"],
    evaluationOrder: "member initializers evaluate top to bottom",
    exampleSource: "const enum Direction { Up, Down = 2 }",
    exampleEnglish: "declare const enum `Direction`\nmembers:\n    member `Up`\n    member `Down` with value number 2",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ModuleDeclaration',
    nodeInterface: 'ts.ModuleDeclaration',
    category: 'declaration',
    typescriptOnly: true,
    canonicalEnglish: "declare namespace / module / global augmentation",
    englishTemplate: "declare [modifier words] (namespace `{name}` | module {string} | global augmentation) / (body: | with no body)",
    children: ["modifiers","name","body"],
    evaluationOrder: "body statements run top to bottom when the module evaluates",
    exampleSource: "namespace app { export const port = 1; }",
    exampleEnglish: "declare namespace `app`\nbody:\n    declare exported constant `port` and initialize it to number 1",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'SourceFile',
    nodeInterface: 'ts.SourceFile',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "whole file",
    englishTemplate: "statements top to bottom; each leading comment renders as its own \"comment:\" line",
    children: ["statements"],
    evaluationOrder: "top to bottom",
    exampleSource: "// entry point\nrun();",
    exampleEnglish: "comment: // entry point\ncall `run` with no arguments",
    semanticInfoRequired: 'none',
    notes: "Comments are reproduced as explicit comment lines, never converted into program facts.",
  },
  {
    syntaxKind: 'ExpressionStatement',
    nodeInterface: 'ts.ExpressionStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "the expression itself",
    englishTemplate: "{expression}",
    children: ["expression"],
    evaluationOrder: "expression evaluates for its effects",
    exampleSource: "notify();",
    exampleEnglish: "call `notify` with no arguments",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'Block',
    nodeInterface: 'ts.Block',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "block",
    englishTemplate: "block: / {statements}",
    children: ["statements"],
    evaluationOrder: "top to bottom",
    exampleSource: "{ setup(); }",
    exampleEnglish: "block:\n    call `setup` with no arguments",
    semanticInfoRequired: 'none',
    notes: "A standalone block statement; function bodies render under \"body:\" instead.",
  },
  {
    syntaxKind: 'EmptyStatement',
    nodeInterface: 'ts.EmptyStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "an empty statement",
    englishTemplate: "an empty statement",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: ";",
    exampleEnglish: "an empty statement",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'IfStatement',
    nodeInterface: 'ts.IfStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "if / then / otherwise",
    englishTemplate: "if {condition} / then: {statements} [/ otherwise: {statements}]",
    children: ["expression","thenStatement","elseStatement"],
    evaluationOrder: "condition, then exactly one branch",
    exampleSource: "if (ready) {\n  start();\n} else {\n  waitMore();\n}",
    exampleEnglish: "if `ready` is truthy\nthen:\n    call `start` with no arguments\notherwise:\n    call `waitMore` with no arguments",
    semanticInfoRequired: 'none',
    notes: "A non-predicate condition is spelled \"… is truthy\".",
  },
  {
    syntaxKind: 'WhileStatement',
    nodeInterface: 'ts.WhileStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "while",
    englishTemplate: "while {condition} / body: {statements}",
    children: ["expression","statement"],
    evaluationOrder: "condition before every pass",
    exampleSource: "while (queue.length > 0) {\n  drain();\n}",
    exampleEnglish: "while property `length` of `queue` is greater than number 0\nbody:\n    call `drain` with no arguments",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'DoStatement',
    nodeInterface: 'ts.DoStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "do / then repeat while",
    englishTemplate: "do: {statements} / then repeat while {condition}",
    children: ["statement","expression"],
    evaluationOrder: "body first, condition after every pass",
    exampleSource: "do {\n  poll();\n} while (pending);",
    exampleEnglish: "do:\n    call `poll` with no arguments\nthen repeat while `pending` is truthy",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ForStatement',
    nodeInterface: 'ts.ForStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "for loop",
    englishTemplate: "for loop / [setup: …] / [continue while …] / [after each pass: …] / body: {statements}",
    children: ["initializer","condition","incrementor","statement"],
    evaluationOrder: "setup once; then condition, body, incrementor per pass",
    exampleSource: "for (let i = 0; i < 3; i++) {\n  step(i);\n}",
    exampleEnglish: "for loop\nsetup:\n    declare variable `i` and initialize it to number 0\ncontinue while `i` is less than number 3\nafter each pass:\n    increment `i` and yield the previous value\nbody:\n    call `step`\n    with argument `i`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ForOfStatement',
    nodeInterface: 'ts.ForOfStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "for each … from iterable",
    englishTemplate: "(for each | for await each) {binding} from iterable {expression} / body: {statements}",
    children: ["awaitModifier","initializer","expression","statement"],
    evaluationOrder: "iterable evaluates once; the binding re-binds per pass",
    exampleSource: "for await (const chunk of stream) {\n  write(chunk);\n}",
    exampleEnglish: "for await each constant `chunk`\nfrom iterable `stream`\nbody:\n    call `write`\n    with argument `chunk`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ForInStatement',
    nodeInterface: 'ts.ForInStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "for each … from the enumerable keys of",
    englishTemplate: "for each {binding} from the enumerable keys of {expression} / body: {statements}",
    children: ["initializer","expression","statement"],
    evaluationOrder: "object evaluates once; keys enumerate per pass",
    exampleSource: "for (const key in config) {\n  print(key);\n}",
    exampleEnglish: "for each constant `key`\nfrom the enumerable keys of `config`\nbody:\n    call `print`\n    with argument `key`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ContinueStatement',
    nodeInterface: 'ts.ContinueStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "continue",
    englishTemplate: "continue [to label `{label}`]",
    children: ["label"],
    evaluationOrder: "transfers control immediately",
    exampleSource: "while (busy) {\n  continue;\n}",
    exampleEnglish: "while `busy` is truthy\nbody:\n    continue",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'BreakStatement',
    nodeInterface: 'ts.BreakStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "break",
    englishTemplate: "break [to label `{label}`]",
    children: ["label"],
    evaluationOrder: "transfers control immediately",
    exampleSource: "while (busy) {\n  break;\n}",
    exampleEnglish: "while `busy` is truthy\nbody:\n    break",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ReturnStatement',
    nodeInterface: 'ts.ReturnStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "return",
    englishTemplate: "return [{expression}]",
    children: ["expression"],
    evaluationOrder: "operand evaluates, then the function returns",
    exampleSource: "function stop() {\n  return;\n}",
    exampleEnglish: "declare function `stop`\nwith no parameters\nbody:\n    return",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'WithStatement',
    nodeInterface: 'ts.WithStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "with scope from",
    englishTemplate: "with scope from {expression} / body: {statements}",
    children: ["expression","statement"],
    evaluationOrder: "scope object evaluates once",
    exampleSource: "with (Math) {\n  round(1);\n}",
    exampleEnglish: "with scope from `Math`\nbody:\n    call `round`\n    with argument number 1",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'SwitchStatement',
    nodeInterface: 'ts.SwitchStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "switch on",
    englishTemplate: "switch on {expression} / when case matches … [/ body: …] / the default case [/ body: …]",
    children: ["expression","caseBlock"],
    evaluationOrder: "discriminant once, then case tests top to bottom",
    exampleSource: "switch (status) {\n  case \"open\":\n    handle();\n    break;\n  default:\n    ignore();\n}",
    exampleEnglish: "switch on `status`\nwhen case matches string \"open\"\nbody:\n    call `handle` with no arguments\n    break\nthe default case\nbody:\n    call `ignore` with no arguments",
    semanticInfoRequired: 'none',
    notes: "A case with no body has no body line — fall-through stays visible.",
  },
  {
    syntaxKind: 'LabeledStatement',
    nodeInterface: 'ts.LabeledStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "labeled",
    englishTemplate: "labeled `{label}` / {statement}",
    children: ["label","statement"],
    evaluationOrder: "the labeled statement runs normally",
    exampleSource: "outer: for (const row of rows) {\n  break outer;\n}",
    exampleEnglish: "labeled `outer`\nfor each constant `row`\nfrom iterable `rows`\nbody:\n    break to label `outer`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ThrowStatement',
    nodeInterface: 'ts.ThrowStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "throw",
    englishTemplate: "throw {expression}",
    children: ["expression"],
    evaluationOrder: "operand evaluates, then control unwinds",
    exampleSource: "throw new Error(\"boom\");",
    exampleEnglish: "throw:\n    construct a new `Error`\n    with argument string \"boom\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TryStatement',
    nodeInterface: 'ts.TryStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "try / on error caught as / catch / finally",
    englishTemplate: "try: {statements} [/ on error caught as {binding} / catch: {statements}] [/ finally: {statements}]",
    children: ["tryBlock","catchClause","finallyBlock"],
    evaluationOrder: "try first; catch only on a throw; finally always",
    exampleSource: "try {\n  risky();\n} catch (failure) {\n  report(failure);\n} finally {\n  cleanup();\n}",
    exampleEnglish: "try:\n    call `risky` with no arguments\non error caught as `failure`\ncatch:\n    call `report`\n    with argument `failure`\nfinally:\n    call `cleanup` with no arguments",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'DebuggerStatement',
    nodeInterface: 'ts.DebuggerStatement',
    category: 'statement',
    typescriptOnly: false,
    canonicalEnglish: "trigger the debugger",
    englishTemplate: "trigger the debugger",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "debugger;",
    exampleEnglish: "trigger the debugger",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ImportDeclaration',
    nodeInterface: 'ts.ImportDeclaration',
    category: 'module',
    typescriptOnly: false,
    canonicalEnglish: "import",
    englishTemplate: "(import | import type) / [the default binding as …] / [the namespace as …] / [named bindings: …] / from {module} [/ with attributes: …] — or \"import for side effects from …\"",
    children: ["importClause","moduleSpecifier","attributes"],
    evaluationOrder: "declaration only; the module loads before the file body runs",
    exampleSource: "import { readFile as read } from \"fs\";",
    exampleEnglish: "import\nnamed bindings:\n    `readFile` as `read`\nfrom string \"fs\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ImportEqualsDeclaration',
    nodeInterface: 'ts.ImportEqualsDeclaration',
    category: 'module',
    typescriptOnly: true,
    canonicalEnglish: "import … as an alias for",
    englishTemplate: "(import | import type) `{name}` as an alias for ({entity name} | require of {module})",
    children: ["name","moduleReference"],
    evaluationOrder: "declaration only",
    exampleSource: "import fs = require(\"fs\");",
    exampleEnglish: "import `fs` as an alias for require of string \"fs\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ExportDeclaration',
    nodeInterface: 'ts.ExportDeclaration',
    category: 'module',
    typescriptOnly: false,
    canonicalEnglish: "export",
    englishTemplate: "(export | export type) [everything] [the namespace as …] [named bindings: …] [from {module}] [with attributes: …]",
    children: ["exportClause","moduleSpecifier","attributes"],
    evaluationOrder: "declaration only",
    exampleSource: "export { helper } from \"./util\";",
    exampleEnglish: "export\nnamed bindings:\n    `helper`\nfrom string \"./util\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ExportAssignment',
    nodeInterface: 'ts.ExportAssignment',
    category: 'module',
    typescriptOnly: false,
    canonicalEnglish: "export as default / export equals",
    englishTemplate: "(export as default | export equals) {expression}",
    children: ["expression"],
    evaluationOrder: "expression evaluates when the module evaluates",
    exampleSource: "export default config;",
    exampleEnglish: "export as default `config`",
    semanticInfoRequired: 'none',
    notes: "`export =` reads \"export equals\", distinct from a default export.",
  },
  {
    syntaxKind: 'NamespaceExportDeclaration',
    nodeInterface: 'ts.NamespaceExportDeclaration',
    category: 'module',
    typescriptOnly: true,
    canonicalEnglish: "export as the global namespace",
    englishTemplate: "export as the global namespace `{name}`",
    children: ["name"],
    evaluationOrder: "declaration only",
    exampleSource: "export as namespace MyLib;",
    exampleEnglish: "export as the global namespace `MyLib`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TypeParameter',
    nodeInterface: 'ts.TypeParameterDeclaration',
    category: 'declaration',
    typescriptOnly: true,
    canonicalEnglish: "type parameter",
    englishTemplate: "[modifier words] type parameter `{name}` [constrained to {constraint}] [with default {default}]",
    children: ["modifiers","name","constraint","default"],
    evaluationOrder: "declaration only",
    exampleSource: "function identity<T>(value: T): T {\n  return value;\n}",
    exampleEnglish: "declare function `identity`\nwith type parameters:\n    type parameter `T`\nparameters:\n    parameter `value` with type `T`\nreturn type:\n    `T`\nbody:\n    return `value`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TypeReference',
    nodeInterface: 'ts.TypeReferenceNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "type … with type argument(s)",
    englishTemplate: "`{typeName}` alone, or type `{typeName}` with type argument(s) {typeArguments}",
    children: ["typeName","typeArguments"],
    evaluationOrder: "declaration only",
    exampleSource: "let pending: Promise<User>;",
    exampleEnglish: "declare variable `pending` with type type `Promise` with type argument `User`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TypePredicate',
    nodeInterface: 'ts.TypePredicateNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "type predicate … is …",
    englishTemplate: "type predicate {parameterName} is {type} | asserts {parameterName} | asserts that {parameterName} is {type}",
    children: ["assertsModifier","parameterName","type"],
    evaluationOrder: "declaration only",
    exampleSource: "function isUser(value: unknown): value is User {\n  return true;\n}",
    exampleEnglish: "declare function `isUser`\nparameters:\n    parameter `value` with type unknown\nreturn type:\n    type predicate `value` is `User`\nbody:\n    return true",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'FunctionType',
    nodeInterface: 'ts.FunctionTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "function type",
    englishTemplate: "function type / (parameters: | with no parameters) / returning {type}",
    children: ["typeParameters","parameters","type"],
    evaluationOrder: "declaration only",
    exampleSource: "let handler: (event: string) => void;",
    exampleEnglish: "declare variable `handler`\nwith type:\n    function type\n    parameters:\n        parameter `event` with type string\n    returning void",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ConstructorType',
    nodeInterface: 'ts.ConstructorTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "constructor type",
    englishTemplate: "[abstract] constructor type / (parameters: | with no parameters) / returning {type}",
    children: ["modifiers","typeParameters","parameters","type"],
    evaluationOrder: "declaration only",
    exampleSource: "let factory: new () => User;",
    exampleEnglish: "declare variable `factory` with type constructor type with no parameters returning `User`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TypeQuery',
    nodeInterface: 'ts.TypeQueryNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "the type of",
    englishTemplate: "the type of `{exprName}`",
    children: ["exprName","typeArguments"],
    evaluationOrder: "declaration only",
    exampleSource: "let sibling: typeof origin;",
    exampleEnglish: "declare variable `sibling` with type the type of `origin`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TypeLiteral',
    nodeInterface: 'ts.TypeLiteralNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "an object type with",
    englishTemplate: "an empty object type | an object type with: {members}",
    children: ["members"],
    evaluationOrder: "declaration only",
    exampleSource: "let point: { x: number; y: number };",
    exampleEnglish: "declare variable `point`\nwith type:\n    an object type with:\n        property `x` with type number\n        property `y` with type number",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ArrayType',
    nodeInterface: 'ts.ArrayTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "array type of",
    englishTemplate: "array type of {elementType}",
    children: ["elementType"],
    evaluationOrder: "declaration only",
    exampleSource: "let names: string[];",
    exampleEnglish: "declare variable `names` with type array type of string",
    semanticInfoRequired: 'none',
    notes: "Distinct from a `type \\`Array\\` with type argument …` reference, mirroring the two source spellings.",
  },
  {
    syntaxKind: 'TupleType',
    nodeInterface: 'ts.TupleTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "tuple type of",
    englishTemplate: "an empty tuple type | tuple type of: {elements}",
    children: ["elements"],
    evaluationOrder: "declaration only",
    exampleSource: "let pair: [string, number];",
    exampleEnglish: "declare variable `pair` with type tuple type of string and number",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'NamedTupleMember',
    nodeInterface: 'ts.NamedTupleMember',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "member … with type …",
    englishTemplate: "(member | optional member | rest member) `{name}` with type {type}",
    children: ["name","type"],
    evaluationOrder: "declaration only",
    exampleSource: "let pair: [name: string, age: number];",
    exampleEnglish: "declare variable `pair`\nwith type:\n    tuple type of:\n        member `name` with type string\n        member `age` with type number",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'OptionalType',
    nodeInterface: 'ts.OptionalTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "optional",
    englishTemplate: "optional {type}",
    children: ["type"],
    evaluationOrder: "declaration only",
    exampleSource: "let pair: [string, number?];",
    exampleEnglish: "declare variable `pair`\nwith type:\n    tuple type of:\n        string\n        optional number",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'RestType',
    nodeInterface: 'ts.RestTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "rest of",
    englishTemplate: "rest of {type}",
    children: ["type"],
    evaluationOrder: "declaration only",
    exampleSource: "let row: [string, ...number[]];",
    exampleEnglish: "declare variable `row`\nwith type:\n    tuple type of:\n        string\n        rest of array type of number",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'UnionType',
    nodeInterface: 'ts.UnionTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "union type of",
    englishTemplate: "union type of: {types}",
    children: ["types"],
    evaluationOrder: "declaration only",
    exampleSource: "let id: string | null;",
    exampleEnglish: "declare variable `id` with type union type of string and null",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'IntersectionType',
    nodeInterface: 'ts.IntersectionTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "intersection type of",
    englishTemplate: "intersection type of: {types}",
    children: ["types"],
    evaluationOrder: "declaration only",
    exampleSource: "let both: Named & Aged;",
    exampleEnglish: "declare variable `both` with type intersection type of `Named` and `Aged`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ConditionalType',
    nodeInterface: 'ts.ConditionalTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "conditional type: if … extends … then … otherwise …",
    englishTemplate: "conditional type: if {checkType} extends {extendsType} then: {trueType} otherwise: {falseType}",
    children: ["checkType","extendsType","trueType","falseType"],
    evaluationOrder: "declaration only",
    exampleSource: "type IsString<T> = T extends string ? true : false;",
    exampleEnglish: "declare type alias `IsString`\nwith type parameters:\n    type parameter `T`\nas:\n    conditional type: if `T`\n    extends string\n    then:\n        true\n    otherwise:\n        false",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'InferType',
    nodeInterface: 'ts.InferTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "infer type parameter",
    englishTemplate: "infer type parameter `{name}` [constrained to …]",
    children: ["typeParameter"],
    evaluationOrder: "declaration only",
    exampleSource: "type Unwrap<T> = T extends Promise<infer U> ? U : T;",
    exampleEnglish: "declare type alias `Unwrap`\nwith type parameters:\n    type parameter `T`\nas:\n    conditional type: if `T`\n    extends:\n        type `Promise`\n        with type argument:\n            infer type parameter `U`\n    then:\n        `U`\n    otherwise:\n        `T`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ParenthesizedType',
    nodeInterface: 'ts.ParenthesizedTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "explicit grouping",
    englishTemplate: "({type}) inline, or \"group of:\" as a block",
    children: ["type"],
    evaluationOrder: "declaration only",
    exampleSource: "let handlers: (() => void)[];",
    exampleEnglish: "declare variable `handlers` with type array type of (function type with no parameters returning void)",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ThisType',
    nodeInterface: 'ts.ThisTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "the `this` type",
    englishTemplate: "the `this` type",
    children: [],
    evaluationOrder: "leaf",
    exampleSource: "class Builder { self(): this { return this; } }",
    exampleEnglish: "declare class `Builder`\nmembers:\n    method `self`\n    with no parameters\n    return type:\n        the `this` type\n    body:\n        return `this`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TypeOperator',
    nodeInterface: 'ts.TypeOperatorNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "the keys of / unique / readonly",
    englishTemplate: "(the keys of | unique | readonly) {type}",
    children: ["type"],
    evaluationOrder: "declaration only",
    exampleSource: "type Keys = keyof User;",
    exampleEnglish: "declare type alias `Keys` as the keys of `User`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'IndexedAccessType',
    nodeInterface: 'ts.IndexedAccessTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "indexed access of … at …",
    englishTemplate: "indexed access of {objectType} at {indexType}",
    children: ["objectType","indexType"],
    evaluationOrder: "declaration only",
    exampleSource: "type Name = User[\"name\"];",
    exampleEnglish: "declare type alias `Name` as indexed access of `User` at string \"name\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'MappedType',
    nodeInterface: 'ts.MappedTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "mapped type with key",
    englishTemplate: "mapped type with key `{name}` / in {constraint} [/ renamed as {nameType}] [/ adding|removing|marked readonly] [/ adding|removing|marked optional] / with value type {type}",
    children: ["typeParameter","nameType","readonlyToken","questionToken","type"],
    evaluationOrder: "declaration only",
    exampleSource: "type Clone<T> = { [K in keyof T]: T[K] };",
    exampleEnglish: "declare type alias `Clone`\nwith type parameters:\n    type parameter `T`\nas:\n    mapped type with key `K`\n    in the keys of `T`\n    with value type indexed access of `T` at `K`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'LiteralType',
    nodeInterface: 'ts.LiteralTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "the literal itself",
    englishTemplate: "{literal}",
    children: ["literal"],
    evaluationOrder: "declaration only",
    exampleSource: "let mode: \"dark\";",
    exampleEnglish: "declare variable `mode` with type string \"dark\"",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'TemplateLiteralType',
    nodeInterface: 'ts.TemplateLiteralTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "template string type joining",
    englishTemplate: "template string type joining: text …, value of type …, …",
    children: ["head","templateSpans"],
    evaluationOrder: "declaration only",
    exampleSource: "type Route = `/api/${string}`;",
    exampleEnglish: "declare type alias `Route`\nas:\n    template string type joining:\n        text \"/api/\"\n        value of type string",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'ImportType',
    nodeInterface: 'ts.ImportTypeNode',
    category: 'type',
    typescriptOnly: true,
    canonicalEnglish: "type imported from",
    englishTemplate: "[the type of] type imported from {module} [member `{qualifier}`] [with type argument(s) …]",
    children: ["argument","qualifier","typeArguments"],
    evaluationOrder: "declaration only",
    exampleSource: "let logger: import(\"./log\").Logger;",
    exampleEnglish: "declare variable `logger` with type type imported from string \"./log\" member `Logger`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'JsxElement',
    nodeInterface: 'ts.JsxElement',
    category: 'jsx',
    typescriptOnly: false,
    canonicalEnglish: "JSX element",
    englishTemplate: "JSX element {tagName} / [with attributes: …] / [children: …]",
    children: ["openingElement","children","closingElement"],
    evaluationOrder: "attributes left to right, then children in order",
    exampleFile: "example.tsx",
    exampleSource: "const el = <section title=\"intro\">Hello {name}</section>;",
    exampleEnglish: "declare constant `el`\nand initialize it to:\n    JSX element `section`\n    with attributes:\n        attribute `title` set to string \"intro\"\n    children:\n        text \"Hello \"\n        the expression `name`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'JsxSelfClosingElement',
    nodeInterface: 'ts.JsxSelfClosingElement',
    category: 'jsx',
    typescriptOnly: false,
    canonicalEnglish: "self-closing JSX element",
    englishTemplate: "self-closing JSX element {tagName} / [with attributes: …]",
    children: ["tagName","attributes"],
    evaluationOrder: "attributes left to right",
    exampleFile: "example.tsx",
    exampleSource: "const el = <input disabled />;",
    exampleEnglish: "declare constant `el`\nand initialize it to:\n    self-closing JSX element `input`\n    with attributes:\n        attribute `disabled`",
    semanticInfoRequired: 'none',
    notes: "A bare attribute (no value) has no \"set to\" clause.",
  },
  {
    syntaxKind: 'JsxFragment',
    nodeInterface: 'ts.JsxFragment',
    category: 'jsx',
    typescriptOnly: false,
    canonicalEnglish: "JSX fragment",
    englishTemplate: "JSX fragment / [children: …]",
    children: ["children"],
    evaluationOrder: "children in order",
    exampleFile: "example.tsx",
    exampleSource: "const el = <><Item /></>;",
    exampleEnglish: "declare constant `el`\nand initialize it to:\n    JSX fragment\n    children:\n        self-closing JSX element `Item`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'JsxExpression',
    nodeInterface: 'ts.JsxExpression',
    category: 'jsx',
    typescriptOnly: false,
    canonicalEnglish: "the expression",
    englishTemplate: "the expression {expression} | the spread expression {expression}",
    children: ["expression"],
    evaluationOrder: "evaluates where it appears",
    exampleFile: "example.tsx",
    exampleSource: "const el = <div>{count}</div>;",
    exampleEnglish: "declare constant `el`\nand initialize it to:\n    JSX element `div`\n    children:\n        the expression `count`",
    semanticInfoRequired: 'none',
  },
  {
    syntaxKind: 'JsxText',
    nodeInterface: 'ts.JsxText',
    category: 'jsx',
    typescriptOnly: false,
    canonicalEnglish: "text",
    englishTemplate: "text {JSON-quoted text}",
    children: [],
    evaluationOrder: "leaf",
    exampleFile: "example.tsx",
    exampleSource: "const el = <p>Hello</p>;",
    exampleEnglish: "declare constant `el`\nand initialize it to:\n    JSX element `p`\n    children:\n        text \"Hello\"",
    semanticInfoRequired: 'none',
    notes: "Whitespace-only JSX text between elements is formatting and is omitted.",
  },
]
