import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import type { Requirement } from '../shared/coverage/types'
import { readDocsCollection } from '../apps/web-server/src/features/coverage/logic/coverage/docs-collection'
import { withFingerprints } from '../apps/web-server/src/features/coverage/logic/coverage/fingerprints'
import { writePrdSummary } from '../apps/web-server/src/features/coverage/logic/coverage/prd-summary-render'

// Regenerate the shipped storefront_journey PRD summary.
//
// The scaffold ships this suite with its Requirements stage already satisfied,
// so `docs/_prd-summary.json` has to exist as a committed template file. Hand-
// writing it is not an option: it carries a docs hash, a requirements-set hash
// and a per-requirement fingerprint, all of which the drift detector compares.
// So it is GENERATED by the product's own writer, from the product's own source
// doc, and the result is committed. `storefront-prd-summary.test.ts` fails if
// the two ever fall out of step.
//
// Run: npm run gen:demo-prd

const HERE = path.dirname(fileURLToPath(import.meta.url))
const TEMPLATES = path.join(HERE, '..', 'templates', 'project')
const FEATURE = 'storefront_journey'
const FEATURE_DIR = path.join(TEMPLATES, 'features', FEATURE)

/** The product repo's own requirements doc — what a Flight's docs stage would
 *  collect. Copied rather than referenced: the feature directory has to be
 *  self-contained once the scaffold lands it in someone's workspace. */
export const SOURCE_DOC = path.join(TEMPLATES, 'demo-app', 'REQUIREMENTS.md')
export const COLLECTED_DOC_NAME = 'storefront_journey-prd.md'

/** Pinned so regenerating produces a byte-identical file — this artifact is
 *  committed, and a wall-clock stamp would churn the diff on every run. */
const GENERATED_AT = '2026-08-07T00:00:00.000Z'

/** The twelve contracts REQUIREMENTS.md describes, one requirement each, in
 *  journey order. Ids are the durable spine the spec's `@req-*` tags point at —
 *  never renumber them. */
export const REQUIREMENTS: Requirement[] = [
  {
    id: 'R1',
    title: 'Catalog serves what it was given',
    text: 'It should return a created product at the price it was given, and list it in the catalog.',
    kind: 'functional',
    happyPath: 'POST a product at 900 cents → 201 with priceCents 900; the product appears in GET /products.',
    pathTypes: ['happy'],
  },
  {
    id: 'R2',
    title: 'Catalog SKU identity',
    text: 'It should derive a stable slug SKU from the product name, because that SKU is the identity inventory consumes.',
    kind: 'functional',
    happyPath: 'Creating "Espresso Beans" yields sku "espresso-beans".',
    pathTypes: ['happy'],
  },
  {
    id: 'R3',
    title: 'Reserving consumes stock',
    text: 'It should reduce a SKU\'s available count by exactly the quantity reserved.',
    kind: 'functional',
    happyPath: 'Reserving 2 units drops available by 2.',
    pathTypes: ['happy'],
  },
  {
    id: 'R4',
    title: 'A discount reaches the total',
    text: 'It should apply the recorded discount percentage to the cart total the customer is charged.',
    kind: 'functional',
    happyPath: 'Two units at 1800 cents with WELCOME10 total 3240 cents.',
    pathTypes: ['happy'],
  },
  {
    id: 'R5',
    title: 'Discount codes replace, never stack',
    text: 'It should let a second discount code replace the first rather than combining the two.',
    kind: 'functional',
    happyPath: 'Applying HALFOFF after WELCOME10 totals 1800 cents, not a combined 60% off.',
    pathTypes: ['happy'],
  },
  {
    id: 'R6',
    title: 'An oversell is refused honestly',
    text: 'It should refuse a reservation larger than the stock on hand and report the count that is genuinely still available.',
    kind: 'functional',
    unhappyPath: 'Reserving 10000 of a SKU with 8 left returns 409 and the unchanged available count.',
    pathTypes: ['sad'],
  },
  {
    id: 'R7',
    title: 'Unknown stock is a missing resource',
    text: 'It should refuse a reservation against a SKU that does not exist as a missing resource, not a malformed request.',
    kind: 'functional',
    unhappyPath: 'Reserving against an unknown SKU returns 404, not 400.',
    pathTypes: ['sad'],
  },
  {
    id: 'R8',
    title: 'A price change persists',
    text: 'It should persist a product price update and return the product at its new price.',
    kind: 'functional',
    happyPath: 'PATCH priceCents 1800 → 2000 returns the product at 2000.',
    pathTypes: ['happy'],
  },
  {
    id: 'R9',
    title: 'Reads agree with charges',
    text: 'It should report, when a cart is read back, the same total checkout will charge — discount included.',
    kind: 'functional',
    happyPath: 'Two units at 2000 cents with WELCOME10 read back as 3600 cents.',
    pathTypes: ['happy'],
  },
  {
    id: 'R10',
    title: 'A deleted product is gone',
    text: 'It should remove the deleted product — and only that product — from the catalog listing.',
    kind: 'functional',
    happyPath: 'DELETE a product → 204, and it no longer appears in GET /products while its neighbours do.',
    pathTypes: ['happy'],
  },
  {
    id: 'R11',
    title: 'A rejected code changes nothing',
    text: 'It should refuse an unknown discount code and leave the discount already on the cart intact.',
    kind: 'functional',
    unhappyPath: 'An unknown code returns 400 and the cart keeps the total its earlier valid code produced.',
    pathTypes: ['sad'],
  },
  {
    id: 'R12',
    title: 'An empty order is refused',
    text: 'It should refuse to place a cart that has no items, and leave the cart open.',
    kind: 'functional',
    unhappyPath: 'Checking out an empty cart returns 409 and the cart status stays "open".',
    pathTypes: ['sad'],
  },
]

export function generate(): { docsHash: string; requirements: number } {
  const docsDir = path.join(FEATURE_DIR, 'docs')
  fs.mkdirSync(docsDir, { recursive: true })
  fs.copyFileSync(SOURCE_DOC, path.join(docsDir, COLLECTED_DOC_NAME))

  const collection = readDocsCollection(FEATURE_DIR)
  const written = writePrdSummary(
    FEATURE_DIR,
    FEATURE,
    withFingerprints(
      {
        requirements: REQUIREMENTS,
        docsHash: collection.docsHash,
        sourceDocs: collection.entries.map((e) => e.relPath),
        generatedAt: GENERATED_AT,
      },
      collection.entries,
    ),
  )
  return { docsHash: written.docsHash, requirements: written.requirements.length }
}

if (process.argv[1] && fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url))) {
  const { docsHash, requirements } = generate()
  console.log(`✔ ${FEATURE}: ${requirements} requirements, docs ${docsHash.slice(0, 12)}…`)
}
